### ISSUE TITLE
On mobile viewports, placement of the "hamburger" menu toggle button could be better

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#103]

**Comment by tbrlpld** [comment]
I think this could use some explanation or a sketch of the desired placement

**Comment by allcaps** [comment]
This came from a comment on https://github.com/wagtail/wagtail/pull/6930

So maybe @thibaudcolas can tell.

**Comment by tbrlpld** [comment]
Ah, I see now... With the large title it pushes the hamburger to the another line. 

<img width="404" alt="Screenshot 2021-04-19 at 22 43 59" src="https://user-images.githubusercontent.com/24797493/115366226-d5277f80-a160-11eb-955a-6f973f9aabe8.png">

I guess we could just hide the title on small screens.

**Comment by Scotchester** [comment]
There's also an accessibility issue related to this that I just discovered: That button has no text in it (or `aria-label`), so it won't be read by screen readers. I will look at fixing in conjunction with this issue.

**Comment by thibaudcolas** [comment]
Fixed in #109.
