### ISSUE TITLE
Increase space after admonition code blocks

### ISSUE THREAD

**Issue by Stormheg** [wagtail/sphinx_wagtail_theme#107]
https://docs.wagtail.io/en/latest/topics/pages.html#inline-models

I think there should be more space between the code block and the text below it.

![image](https://user-images.githubusercontent.com/13856515/116230054-7a40ea00-a757-11eb-8efc-1d3ee5061a97.png)

**Comment by PaarthAgarwal** [comment]
I'm on it.

**Comment by PaarthAgarwal** [comment]
I believe this one has been resolved already.
![image](https://user-images.githubusercontent.com/86092410/160785473-2cca8602-ba79-4976-b004-17d0a6dd470a.png)

**Comment by Stormheg** [comment]
Looks like the text is now outside the admonition. Perhaps the switch from Recommonmark to MyST (https://github.com/wagtail/wagtail/issues/8074) has something to do with this?
