### ISSUE TITLE
Increase contrast of inline code elements

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#11]
Based on: https://github.com/wagtail/wagtail/issues/6793

A design proposal could be helpful. 

Current Wagtail docs:
![image](https://user-images.githubusercontent.com/24797493/110294516-0de60d80-7f94-11eb-972b-98f17825f830.png)

Current Typo3 based theme:
![image](https://user-images.githubusercontent.com/24797493/110294584-1fc7b080-7f94-11eb-8f55-5821d1bbb6f8.png)

**Comment by vsalvino** [comment]
Ditto contrast of admonitions as pointed out in #119 . Probably worth doing a contrast-related changeset (which might benefit from a designer's eye if there are to be any color palette changes)
