### ISSUE TITLE
Sticky main navigation (on the left)

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#12]
Based on: https://github.com/wagtail/wagtail/issues/6793

We need to discuss if the main navigation should be sticky. I think it should.

**Comment by gasman** [comment]
@DanielSwain has also requested this by email, and offered the following fix:

> If someone would simply put sticky-top where I show it, then the left navigation wouldn’t scroll out of view when scrolling down the page.
![image001](https://user-images.githubusercontent.com/85097/123311927-9c6ca380-d51f-11eb-901b-94a615cae0d6.png)
> Example of nav bar staying right where I want it when I’ve scrolled far down a long page.
![image002](https://user-images.githubusercontent.com/85097/123311981-a9899280-d51f-11eb-9cf8-32d6c1007031.png)

**Comment by DanielSwain** [comment]
I just submitted a [pull request](https://github.com/wagtail/sphinx_wagtail_theme/pull/110) for this feature request.
