### ISSUE TITLE
Font licensing issue (!!!)

### ISSUE THREAD

**Issue by vsalvino** [wagtail/sphinx_wagtail_theme#120]
I noticed that the font **"Apercu Pro"** is included with this package. The font files do not contain a license file aside them, which is a bit unusual. Upon further research it seems that the fonts are sold by Colophon Foundry (https://www.colophon-foundry.org/typefaces/apercu/) and from what I can tell are NOT freely available.

I do not know if this theme carries a license to distribute these fonts. If so, then this theme needs to include such a license. However I would not want theme users to suddenly get hit with copyright infringement lawsuits (it has happened to me before, and can be really destructive). Yes, something as simple as distributing an unlicensed font on your website, even unknowingly so, can wreak legal havoc.

So the 3 options are:
* Include a license which permits use and redistribution.
* Remove the font and include a more liberally licensed alternative (Source Sans Pro, or Overpass, seem like similar alternatives).
* Do not provide a font; use a web-safe/system font stack. This is a popular light-weight option, and makes it easy for theme users to override our theme choice. (Trebuchet MS is web-safe and looks loosely similar)

From the Torchbox viewpoint, Torchbox can continue using Apercu Pro on the Wagtail docs, using its own license, but will have to override whatever font is provided by this theme.

**Comment by Scotchester** [comment]
😬 Good catch.

> So the 3 options are:
> 
> * Include a license which permits use and redistribution.

They don't appear to offer such a license.

> * Remove the font and include a more liberally licensed alternative (Source Sans Pro, or Overpass, seem like similar alternatives).
> 
> * Do not provide a font; use the system font stack. This is a popular light-weight option, and makes it easy for theme users to override our theme choice.

I think we should do this last option in the immediate term, as a decision on including an alternate font may take a while.

We should do that ASAP and then follow these instructions to purge the font files from the repo history: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

**Comment by vsalvino** [comment]
I made a PR, and ended up replacing it with Source Sans, which looks similar enough that it shouldn't be too jarring.
