### ISSUE TITLE
rst-content styles are not being used

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/sphinx_wagtail_theme#131]
Our theme contains extensive customisations for content styling in https://github.com/wagtail/sphinx_wagtail_theme/blob/a056b6e941e6a9af4b2f32ab157ff95613a0ca55/sass/_component_rst.scss.

It looks like they aren’t being used on docs.wagtail.org, because nothing is outputting this `rst-content` class. Here is what it looks like when manually adding it:

![rst-content](https://user-images.githubusercontent.com/877585/157435540-e671b91b-c8d2-49f7-b71b-4e2f634808b8.gif)

I’m not entirely sure whether us not using those styles is intentional or not. Our autodocs styles at least could use a bit more structure.

**Comment by tbrlpld** [comment]
Wow. That looks so much better! We should definitely add that. The auto docs have been a pain for a bit.

**Comment by PaarthAgarwal** [comment]
I'll give it a shot.

**Comment by PaarthAgarwal** [comment]
![image](https://user-images.githubusercontent.com/86092410/160791416-028daa72-20fa-4350-80d4-daf01d77214d.png)

The blue box appearing around italicized text looks good, but the change in the style of sub-headings and links i.e

![image](https://user-images.githubusercontent.com/86092410/160791684-ed4e443e-8df3-4108-8ce6-c035c4a146e8.png)
are they desirable?

**Comment by tbrlpld** [comment]
I think definitely desirable! Being able to see those is a big issue for me in the current design.
