### ISSUE TITLE
Adopt MyST parser in place of recommonmark

### ISSUE THREAD

**Issue by lb-** [wagtail/sphinx_wagtail_theme#133]
We should adopt MyST Parser in our Wagtail Sphinx theme, as it has now been adopted in Watail core.

https://myst-parser.readthedocs.io/en/latest/

This way we can triage and add core styling for these issues.

https://github.com/executablebooks/MyST-Parser/issues/533
https://github.com/executablebooks/MyST-Parser/issues/534

See Wagtail adoption PR https://github.com/wagtail/wagtail/pull/8084

_Originally posted by @lb- in https://github.com/wagtail/wagtail/pull/8101#r823493348_

**Comment by Hitansh-Shah** [comment]
I will give this a go.

**Comment by lb-** [comment]
Turns out this was a bit of a key dependency for other issues, so I have given a go at this
https://github.com/wagtail/sphinx_wagtail_theme/pull/142

**Comment by Hitansh-Shah** [comment]
Got it! No issue 🙌
