### ISSUE TITLE
Dark mode for docs

### ISSUE THREAD

**Issue by p0lygun** [wagtail/sphinx_wagtail_theme#135]
### Is your proposal related to a problem?

The docs at (docs.wagtail.org) should have a dark theme as its much easier to read the text in dark mode

### Describe the solution you'd like

There should be a switchable (light/dark (more ?)) theme for the docs

### Describe alternatives you've considered

To make the work easier, we can use "Dark reader" dynamic theme generation to make the color pallet for the dark theme

### Additional context
I have previously made dark themes for custom sphinx themes, and I feel comfortable working with this 😄, 
and I wanted to open this issue in wagtail/wagtail, but this felt a better place for it

**Comment by Stormheg** [comment]
Hi @p0lygun, this repository is definitely the place for a feature request like this!

Dark mode would be a welcome addition. We could probably use the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query to conditionally apply a dark color scheme. Having an option to manually switch between dark/light mode is quite a common feature in other documentation themes, so having something like that would be nice.

One thing to consider is that docs.wagtail.org uses Algolia for search autocomplete. Not sure if we are able to change the colors of that - I don't have experience with Algolia.

@p0lygun would you be happy to work on this?

**Comment by p0lygun** [comment]
Yes, I'll open a PR for this soon 😀

**Comment by lb-** [comment]
@p0lygun if at all possible - can the PR also involve pulling up our colours into CSS custom variables. 

This further enhances the themeability of this project with some simple css variable changes being able to change the visuals. 

I would assume we would have normal and dark variants of each variable. 

This enhancement is not a blocker for dark mode but just might be easier to do at the same time.

**Comment by p0lygun** [comment]
first i would like to apologize for not working on this, i had my exams going on so was not able to put time into this, 
second i am going to use CSS variables, 
@lb-  i will start working on this tomorrow as i still need to write the application for my gsoc entry on  "Apply new page editor UX to all of Wagtail" :smile: 
PS :- [Kivy's dark mode for example](https://github.com/kivy/kivy/blob/master/doc/sources/.static/fresh.css#L13)

**Comment by lb-** [comment]
@p0lygun  - no need to apologise at all, do not feel in any way that you are on a contract or anything for this. It is open source and a community where we are all volunteers trying to help where we can.

If you get to do this, awesome, if not - it is OK.

Thank for the update though and good luck on your application.

**Comment by vsalvino** [comment]
If it's any use, I implemented a user-selectable light/dark mode switcher on my "hobby" sphinx theme: https://github.com/vsalvino/sphinx-library

A welcome addition would be to initialize it based on the prefers-color-scheme.
