### ISSUE TITLE
Ensure syntax highlighting is loaded

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#14]
Based on https://github.com/wagtail/wagtail/issues/6793

There had been an issue:
>  syntax highlighting failing to initialize due to a JS syntax error. there is some template syntax issue here: https://github.com/allcaps/wagtail/blob/docs-theme/docs/_templates/layout.html#L175-L178

**Comment by thibaudcolas** [comment]
Looks like this is fixed!
