### ISSUE TITLE
Hard to read syntax highlighting

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#147]
<img width="1548" alt="Screen Shot 2022-04-05 at 2 58 10 PM" src="https://user-images.githubusercontent.com/24797493/161856987-98393ec9-91a8-4d71-aec2-1dddaf1ab5d1.png">

**Comment by lb-** [comment]
Hmm - this may have happened when we added the `.rst` root class
https://github.com/wagtail/sphinx_wagtail_theme/pull/136

Maybe we need to revise or remove this section?

https://github.com/wagtail/sphinx_wagtail_theme/blob/main/sass/_component_rst.scss#L23-L49

**Comment by tbrlpld** [comment]
Yea, why was that changes anyhow? The previous syntax highlights that are currently active in the Wagtail docs look fine to me.

**Comment by lb-** [comment]
I have a fix I think, we have to set `pygments_style` to `None` we have now got our own pygments styles and the Sphinx ones are not required.

I think this happened as part of the update to the latest Sphinx version and not the rst root class.
