### ISSUE TITLE
Link style broken on Safari

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#155]
The underlines are not showing up at all. 

I know there might be an issue with Safari and the underline offset, but we would want the lines to show up at all at least. 

<img width="1762" alt="Screen Shot 2022-04-07 at 3 10 24 PM" src="https://user-images.githubusercontent.com/24797493/162327953-034c47d0-c4ca-4b17-9635-9119b3e91908.png">

**Comment by PaarthAgarwal** [comment]
This must be because of we switched to underline style instead of border. Safari and internet explorer cause issue with new short hand text decoration. One potential fix can be to write styles separately like this

    text-decoration-line: underline;
    text-decoration-style: solid;
    text-decoration-color: green;
Reference: https://www.cssmine.com/blog/2020-03-30-css-text-decoration-family-not-just-for-underlining-links#text-decoration-the-main-shortcut-and-the-main-issue

**Comment by nutjob4life** [comment]
Is this live? The dark mode seems to indicate it might be; see the following screen shot:

![Screen Shot 2022-09-09 at 10 36 58 AM](https://user-images.githubusercontent.com/814813/189389645-7825558a-d564-4a15-bfab-6e0b782f8304.png)

On [this page](https://docs.wagtail.org/en/stable/releases/4.0.html) the three links in the magenta oval should all appear as hyperlinks; c.f. also @tbrlpld's mention at the bottom of the shot 😉

**Comment by tbrlpld** [comment]
Yes it should be live, but when I fixed the link style there was no dark mode yet. So this would be better addressed to whoever did the dark mode.

**Comment by nutjob4life** [comment]
Thanks @tbrlpld. I've submitted a [fresh ticket](https://github.com/wagtail/sphinx_wagtail_theme/issues/206). Maybe @lb- or @vsalvino can take a peek! 🫣

**Comment by lb-** [comment]
yet another fix up for this - hopefully third time is a charm :D 

https://github.com/wagtail/sphinx_wagtail_theme/pull/207
