### ISSUE TITLE
Screenshot with Droste effect

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#156]
Just for the fun of it...

It would be nice if we could have [droste-effect](https://en.wikipedia.org/wiki/Droste_effect) on the documentation screenshot.

See [the screenshot](https://sphinx-wagtail-theme.readthedocs.io/en/latest/).

If visual changes happen, we have to recreate the screenshot. I'd suggest a Pillow script and a clear instruction to make creating the screenshot repeatable.

Mockup:
<img width="1512" alt="droste" src="https://user-images.githubusercontent.com/1969342/162330525-6afbb090-6194-45e1-ab69-2fdd8703b833.png">

**Comment by anujaraj** [comment]
Can I work on this? 
Though I did not understand it exactly. Should be make just a UI design of screenshot change?

**Comment by allcaps** [comment]
Yes, you can!

Realise that this is a nice to have with super low priority. It is a fun coding exercise. Nothing more.

**Comment by tbrlpld** [comment]
We have removed the screenshot from the docs (which I also prefer as this was always confusing to me). I think this can be closed now.
