### ISSUE TITLE
Package lock json version changes

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/sphinx_wagtail_theme#164]
While doing `make setup,` the package-lock.json changes to "lockfileVersion": 2  while using node 16. But if I use node 14, the "lockfileVersion": 1 remains the same. I've been observing this behavior since https://github.com/wagtail/sphinx_wagtail_theme/commit/f7b5dd645114a3facb02647052d91d530a11735b.

Warning in terminal:
![image](https://user-images.githubusercontent.com/86092410/166520790-0fbeb569-28da-4fd3-8ef5-2cea2c18ebe5.png)

Changes in package-lock.json:
![image](https://user-images.githubusercontent.com/86092410/166521092-bf55e656-7b9f-4964-81d9-5056d4973398.png)

Tested on Ubuntu 20.03 LTS, using Node 16.
I have discussed and confirmed this issue is reproducible.

**Comment by lb-** [comment]
Feel free to do a PR for this
