### ISSUE TITLE
Deemphasize "page content" navigation font

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#20]
Based on https://github.com/wagtail/wagtail/issues/6793

>  Consider going a bit less black with the Page contents section, to make it less distracting and indicate that it’s ‘secondary’ content

I guess something like a lighter font color could be good. This should be revised after the design proposal is implemented (see #10 )

Ref, we decreased the font size here, it works pretty well. https://wagtail--6792.org.readthedocs.build/en/6792/getting_started/tutorial.html

**Comment by PaarthAgarwal** [comment]
I want to work on this issue. Please provide some more info on it.

**Comment by tbrlpld** [comment]
You can have a look at the original design in the issue linked in the description.

**Comment by PaarthAgarwal** [comment]
I understand now. How to set up the codebase for this repository?

**Comment by tbrlpld** [comment]
Have you checked the docs? https://sphinx-wagtail-theme.readthedocs.io/en/latest/development.html

**Comment by PaarthAgarwal** [comment]
Checked now. Thank you for pointing out!

> Have you checked the docs? https://sphinx-wagtail-theme.readthedocs.io/en/latest/development.html

**Comment by PaarthAgarwal** [comment]
I was trying to make docs but I am getting this error:
![image](https://user-images.githubusercontent.com/86092410/160765354-d03045f6-ab9c-411d-b703-1bc2f6ada331.png)
(Using Node v16, on Ubuntu VM)

**Comment by Stormheg** [comment]
Hey @PaarthAgarwal 👋 

I merged some PRs by @lb- and https://github.com/wagtail/sphinx_wagtail_theme/pull/142 does indeed fix the jinja2 error message for me.

**Comment by PaarthAgarwal** [comment]
That's great @Stormheg. Building docs right now!

**Comment by PaarthAgarwal** [comment]
> Hey @PaarthAgarwal 👋
> 
> I merged some PRs by @lb-, and #142 does indeed fix the jinja2 error message for me.

The build succeeded @Stormheg. I was expecting a server to start, but it says this:
![image](https://user-images.githubusercontent.com/86092410/161689739-0198c7d3-491a-41ed-8042-c86dc860432d.png)
To inspect the changes, should I be opening one of the HTML files manually. Right?

**Comment by PaarthAgarwal** [comment]
@tbrlpld, can we use this color for deemphasizing page content navigation font as well?
![image](https://user-images.githubusercontent.com/86092410/161691886-46c16ada-d7da-40dd-8e48-4a567582dbe9.png)

**Comment by tbrlpld** [comment]
Sounds good @PaarthAgarwal

**Comment by PaarthAgarwal** [comment]
I was trying to add the above mentioned color in `_component_toc.scss` but ` _component_links.scss ` keeps overriding it. Any fix for it?

**Comment by tbrlpld** [comment]
Hm. That seem unlikely.  `_component_links.scss` only targets the `a` element. Any selector that is more specific (e.g. a `class` should be overriding it. Are you sure that is where it is coming from?

**Comment by PaarthAgarwal** [comment]
> Hm. That seem unlikely. `_component_links.scss` only targets the `a` element. Any selector that is more specific (e.g. a `class` should be overriding it. Are you sure that is where it is coming from?

I think so too. Have a look
![image](https://user-images.githubusercontent.com/86092410/162558766-0e4d8ca2-5169-44fc-8f87-329d60ef5728.png)

**Comment by tbrlpld** [comment]
Wait, we know it overriding the default link style because it does not have an underline. What ever is removing the underline should also be able to override the color.

**Comment by PaarthAgarwal** [comment]
Pro move!
