### ISSUE TITLE
Scrollbars appearance in Darkmode

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/sphinx_wagtail_theme#204]
There comes a point when there are 3 vertical scrollbars and 1 horizontal scrollbar on one page, which looks a bit odd, particularly in dark mode.

In dark mode:
![image](https://user-images.githubusercontent.com/86092410/186440435-c3b39cf3-3a2b-4df1-a35f-c005fc622fd6.png)

In light mode:
![image](https://user-images.githubusercontent.com/86092410/186440693-f64ec2c4-f0f5-4e15-89fe-7a40ec08e8d0.png)

Quick fixes I have in mind:
1. Change the colour of scrollbars for dark mode.
2. Make it slimmer, more transparent and may even make the slider a bit curved.

## Actions

1. Work out why the scrollbar on the TOC is showing a horizontal scroll and ensure that it no longer does that, content should wrap in this container.
2. Potential - add `scrollbar-width: thin;` to the inner and main TOC containers with a note about progressive adoption

**Comment by tbrlpld** [comment]
Can you override the system scroll bar styles?

Why is there even scroll bars around the page TOC? I feel having the page TOC static would be ok and not as annoying as the previously static main TOC. And the horizontal scrolling should definitely be avoided.

**Comment by PaarthAgarwal** [comment]
> Can you override the system scroll bar styles with CSS alone?
> 
Yes, I think we can. 
https://css-tricks.com/almanac/properties/s/scrollbar-color/
> Why is there even scroll bars around the page TOC? 

I added it because there was an issue for it
https://github.com/wagtail/sphinx_wagtail_theme/issues/9

**Comment by tbrlpld** [comment]
Ah, fair enough. I forget which page was the use case. 

But i guess preventing horizontal would still be good

**Comment by lb-** [comment]
I agree preventing horizontal scrolling would be good and an action from this issue.

I am not convinced styling the scrollbar is a good option, I think that it can come across as tacky and it works against the OS's decision on styling here.

However, we could look at just using the slimmer scrollbar-width option.

* https://css-tricks.com/almanac/properties/s/scrollbar-width/
* https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
* https://caniuse.com/?search=scrollbar-width

But it might be a while before browsers support it, however, it could be added with a comment that it will work as browsers adopt it.
