### ISSUE TITLE
Safari: Links invisible on dark mode docs, barely visible in light mode

### ISSUE THREAD

**Issue by nutjob4life** [wagtail/sphinx_wagtail_theme#206]
In #155, hyperlinks were undifferentiated from other text when viewing on Safari. @tbrlpld addressed this, but then dark mode got implemented, and now links are once again largely invisible on Safari.

Take a look at a screenshot of [this page](https://docs.wagtail.org/en/stable/releases/4.0.html) in dark mode from Safari 15.6.1 on macOS 12.5.1:

![Screen Shot 2022-09-09 at 10 36 58 AM](https://user-images.githubusercontent.com/814813/189415193-9044fc06-69cd-43a3-823f-a99bb80e1856.png)

These three bullets should all be hyperlinks, but lack any decoration.

In light mode, they do appear in a slightly different font color:

![Screen Shot 2022-09-09 at 12 55 05 PM](https://user-images.githubusercontent.com/814813/189415283-22e96241-0e1c-4982-940c-6569bd333f2a.png)

However, the color lacks the contrast difference from the body text needed to truly indicate they're navigable (Section 508 issue).

**Comment by lb-** [comment]
Fix up for this https://github.com/wagtail/sphinx_wagtail_theme/pull/207
