### ISSUE TITLE
Change Note and Warnings color

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#21]
Based on https://github.com/wagtail/wagtail/issues/6793

>  Colours of notes and info blocks clash with Wagtail teal

A design proposal would be helpful. Might also need reconsideration after #10 is implemented.

**Comment by PaarthAgarwal** [comment]
Does this issue still persists after the implementation on #137?

**Comment by lb-** [comment]
Closed via e63030b7f56b4a73f8e59e41168c9ddfab3db3f8 https://github.com/wagtail/sphinx_wagtail_theme/pull/137

Thanks @PaarthAgarwal
