### ISSUE TITLE
Dark mode flashes to light mode on page load

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#213]
When navigating around the docs site in dark mode, the pages load in light mode first and then flash to dark. I find this pretty irritating. This may also be an accessibility issue for users sensitive to flashes and motion etc. 

https://user-images.githubusercontent.com/24797493/191531643-33eebfe0-60ab-4049-a3c0-801b65bdf26f.mov

Using `prefers-color-scheme` may help us avoid this: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme. 

We might want to allow to  override the setting with JS. But, but I am not sure who we can avoid the flashes in that case 🤔 But other sites manage it too. Do we need the manual override?

**Comment by tbrlpld** [comment]
Looks like [MDN](https://developer.mozilla.org) uses `prefers-color-scheme` as well as an entry in local storage. They somehow manage to not flash between page loads.

**Comment by tbrlpld** [comment]
Looks like they use an inline script at the top of the body to control what renders. I guess the script is blocking the rendering until it finishes and that is how they prevent the flash:
```html
<body>
    <script>
    document.body.addEventListener("load", (t => {
        t.target.classList.contains("interactive") && t.target.setAttribute("data-readystate", "complete")
    }), {
        capture: !0
    });
    const c = {
        light: "#ffffff",
        dark: "#1b1b1b"
    };
    if (window && document.documentElement)
        try {
            const t = window.localStorage.getItem("theme");
            t && (document.documentElement.className = t, document.documentElement.style.backgroundColor = c[t])
        } catch (t) {
            console.warn("Unable to read theme from localStorage", t)
        }
    </script>
   ...
```

**Comment by lb-** [comment]
Yeah, what is weird is that it was working really well locally for me - no matter what got loaded in what order but then when deployed to the docs it was not working.

I have been meaning to raise this bug - thanks @tbrlpld 

My initial guess is that the script is loaded differently in the Wagtail template code (maybe at the end of the body) but in the local dev it is at the start of the DOM.

But have not looked any further, maybe a rework of the code is needed.

**Comment by lb-** [comment]
I think we will likely need to split the JS into two scripts, one that is blocking (in the head, `core.js` or `head.js`?) and one that is the existing `theme.js`.

https://dev.to/ayc0/light-dark-mode-avoid-flickering-on-reload-1567

We should also wrap the localStorage reading in a try/catch.

**Comment by tbrlpld** [comment]
Maybe even named bluntly `blocking.js` with a warning inside that this should only be used for very critical JS that definitely needs to run before the page rendering (as in this case).

**Comment by lb-** [comment]
Yeah I like this idea.

**Comment by lb-** [comment]
Some good reference implementations of dark mode. 

- https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/main/src/dark-mode-toggle.mjs
- https://github.com/anatoliygatt/dark-mode-toggle/tree/master/src

**Comment by lb-** [comment]
PR up https://github.com/wagtail/sphinx_wagtail_theme/pull/217
