### ISSUE TITLE
Add hover state to navigation

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#22]
Based on https://github.com/wagtail/wagtail/issues/6793

The main navigation needs a hover state.  

We need to define what should the hover state do? Change link color? Show/hide underline?

**Comment by PaarthAgarwal** [comment]
Can we do this for hover in docs?

https://user-images.githubusercontent.com/86092410/159133220-58d72061-cefb-4ff2-bdc8-628b375913ce.mp4

**Comment by PaarthAgarwal** [comment]
@tbrlpld I was checking out https://wagtail.org/about-wagtail/. For navbar hover, they make the underline appear below text, while for other links, they change the underline color to red.

**Comment by tbrlpld** [comment]
I am not sure the red is actually intentional. It does not appear anywhere else in the brand colours. I think we should actually reduce the number of colours we are using and not expand them further.

**Comment by PaarthAgarwal** [comment]
How about changing the text color to teal (primary color of docs) on hover?

**Comment by tbrlpld** [comment]
Yea, that sounds good. Maybe with dark teal as the active state too.

**Comment by PaarthAgarwal** [comment]
On second thought, Wagtail UI is replacing teal with indigo. Can we go for indigo?

**Comment by tbrlpld** [comment]
Let's do the same thing as for normal links
