### ISSUE TITLE
Remove `quoteblock` wrapping of auto-generated documentation

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#24]
Based on https://github.com/wagtail/wagtail/issues/6793

Example: https://wagtail--6792.org.readthedocs.build/en/6792/reference/hooks.html#register-snippet-action-menu-item

**Comment by Stormheg** [comment]
Appears resolved in the current PR https://wagtail--6930.org.readthedocs.build/en/6930/reference/hooks.html#register-snippet-action-menu-item

**Comment by Stormheg** [comment]
Going to close this now as the issue appears resolved
