### ISSUE TITLE
Set up pull request documentation preview

### ISSUE THREAD

**Issue by Stormheg** [wagtail/sphinx_wagtail_theme#34]
It would be great to have the documentation built on pull requests like described here: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by thibaudcolas** [comment]
This is Done™, I pushed straight to `main` as I needed to test the results directly in Read the Docs.

Note Read the Docs doesn’t support running front-end tooling, so although there are advantages to using it to match the Wagtail docs, we may want to set up Netlify for this project.
