### ISSUE TITLE
Autodoc white text

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#42]
Ref https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/74

**Comment by tbrlpld** [comment]
Here is the example: https://sphinx-wagtail-theme.netlify.app/sphinx_wagtail_theme.html

**Comment by tbrlpld** [comment]
This needs to be fixed for the Wagtail PR as well. Here is an example with the white text in the Wagtail docs:

https://wagtail--6930.org.readthedocs.build/en/6930/reference/pages/model_recipes.html
