### ISSUE TITLE
Code snippets copy to clipboard

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#45]
Ref: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/22

**Comment by lb-** [comment]
https://sphinx-copybutton.readthedocs.io/en/latest/

**Comment by thibaudcolas** [comment]
Note from the Wagtail issue – @mohammadareeb95 is working on this :) @mohammadareeb95 make sure to check out the link shared by LB above, with the package we could install that does exactly this.

**Comment by mohammadareeb95** [comment]
![image](https://user-images.githubusercontent.com/77102111/195535709-8321f7ba-9c3f-4ccd-8076-b30fc8d59527.png)

**Comment by lb-** [comment]
Nice!

**Comment by thibaudcolas** [comment]
🙌  great stuff

**Comment by mohammadareeb95** [comment]
_Install dependency_ 

You can install sphinx-copybutton with pip:
`pip install sphinx-copybutton`

Or with conda via conda-forge:
`conda install -c conda-forge sphinx-copybutton`

PR - https://github.com/wagtail/sphinx_wagtail_theme/pull/219

**Comment by lb-** [comment]
fixed via https://github.com/wagtail/sphinx_wagtail_theme/pull/219 2d5b980d1fb66f8007696a95c9be791dbfd23f04
