### ISSUE TITLE
Font sizes and color according to design

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#60]
https://www.figma.com/file/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-wagtail.io?node-id=0%3A1

**Comment by lb-** [comment]
Going to close this as resolved via the adoption of Wagtail's fonts and colours. 

https://github.com/wagtail/sphinx_wagtail_theme/pull/194

I think that a y further 'design system' work will be done via the adoption of the Wagtail design system as taking priority over some of the original global sizes for fonts. 

https://github.com/wagtail/sphinx_wagtail_theme/issues/172
