### ISSUE TITLE
Warning and Notes according to design

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#61]
https://www.figma.com/file/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-wagtail.io?node-id=1%3A2

**Comment by PaarthAgarwal** [comment]
I don't see any warning in docs. Should it be added?

**Comment by lb-** [comment]
https://sphinx-wagtail-theme.readthedocs.io/en/latest/examples/admonitions.html

Or

https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html?highlight=warning#note-and-warning-call-outs (click `rendered output` to see)

**Comment by PaarthAgarwal** [comment]
Ahh, I see.
