### ISSUE TITLE
Add top and bottom margin around images

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#72]
Currently, the images appear very close to the text. 

E.g. https://wagtail--6930.org.readthedocs.build/en/6930/editor_manual/finding_your_way_around/the_explorer_page.html#

**Comment by kkartik07** [comment]
@tbrlpld This link takes me to missing page, so I can't exactly find what the issue is. Please provide me with some more information and relevant link.

**Comment by tbrlpld** [comment]
It appears this has been fixed.
