### ISSUE TITLE
Fix version picker

### ISSUE THREAD

**Issue by Stormheg** [wagtail/sphinx_wagtail_theme#74]
Version picker styling is currently broken

![image](https://user-images.githubusercontent.com/13856515/113113934-205a0c80-920b-11eb-88fc-6317b38673f8.png)

**Comment by Stormheg** [comment]
I think it's likely that we're not loading the version picker styling

**Comment by thibaudcolas** [comment]
Looking at https://sphinx-wagtail-theme.readthedocs.io/en/latest/ this seems to be resolved.
