### ISSUE TITLE
Remove header links

### ISSUE THREAD

**Issue by allcaps** [wagtail/sphinx_wagtail_theme#75]
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_theme_options

I think this should remove the links from the header.

```python
# conf.py
html_theme_options["header_links"] = ""
```

**Comment by PaarthAgarwal** [comment]
Is it still open?

**Comment by lb-** [comment]
@PaarthAgarwal  I think this is phrased more like a question, so maybe if you don't mind can you do a screenshot of the header before & after the setting change (just change it locally on your machine).

Also include small and large breakpoint variants.

We may find this is no longer needed or wanted.

**Comment by PaarthAgarwal** [comment]
Sure. Can you also provide some context about what this is trying to solve or change?

**Comment by lb-** [comment]
I do not know sorry, @allcaps may add some insights when he is online next

**Comment by PaarthAgarwal** [comment]
Sure

**Comment by allcaps** [comment]
I can't recall this is still broken.

This was closed in the project. I don't get why this issue isn't closed automatically.
