### ISSUE TITLE
Fix link style

### ISSUE THREAD

**Issue by Stormheg** [wagtail/sphinx_wagtail_theme#78]
- [x] links are not very recognisable (especially when the color temperature of your screen is very warm, e.g. at night) 
- [ ] links should have a visited style

**Comment by PaarthAgarwal** [comment]
Which color would you prefer for the visited links? 
Currently, the visited color is the same as the hover color, and I am creating a PR to change the hover color to teal as per my discussion in #22, which will also change the color of the visited links to teal.

**Comment by Stormheg** [comment]
@tbrlpld @thibaudcolas do you have any thoughts on what styling would work best for visited links? 

Happy to hear thoughts from anyone, no just the two people I pinged 😄

**Comment by PaarthAgarwal** [comment]
Can we italicize the visited link text?

**Comment by lb-** [comment]
I would recommend against using italicize - this can cause odd issues with the exact widths of the links and also may not translate well in the future (i.e. italics do not mean the same thing to everyone and some languages do not support this in their fonts).

**Comment by tbrlpld** [comment]
It might be time to create a color scale for the theme. Then we can easily pick from the range of defined colors. 

I’ll see if I can find a little time to put one together, based on the colors we already use.

**Comment by Stormheg** [comment]
That would be amazing, thanks @tbrlpld 👍

**Comment by PaarthAgarwal** [comment]
I gave it some thought, and I think whichever color we end up using for visited links, we'll be creating a 'chromatic overload' having black for the normal state, teal for hover, dark teal for active, and another color for visited links, i.e., four different colors in content navigation.

**Comment by Scotchester** [comment]
I think I agree. Most websites don't use visited link styling these days, and particularly in documentation, I'm not sure if that would be useful or just distracting.
