### ISSUE TITLE
Hide project name in header in smaller view ports

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#81]
A long title can push the toggle into another row, making the header tall and awkward looking.

![image](https://user-images.githubusercontent.com/24797493/113927694-843f8080-9789-11eb-846c-2a141c185678.png)

**Comment by thibaudcolas** [comment]
This seems to have been addressed. The project name will wrap into multiple lines on smaller viewports, which seems correct to me:

![swt-81](https://user-images.githubusercontent.com/877585/223712253-df0f9f3d-c546-4eaa-9a91-95035999f108.png)
