### ISSUE TITLE
Make the layout screen filling

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#83]
When I updated the layout, I guess I was interpreting the design wrong.

For some reason I was interpreting it as a centered design. But, it does turn out that the centering is wasting a bunch of space. 

Especially with the bootstrap breakpoints, there are many screen sizes where a lot of space is wasted. 

The layout should be updated to actually follow the design. 

https://www.figma.com/file/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-wagtail.io?node-id=0%3A1

**Comment by Stormheg** [comment]
I received the same feedback from a friend over IM.

> (paraphrased) the content of the new docs is pushed over to the right a lot

![signal-2021-04-08-121420_002](https://user-images.githubusercontent.com/13856515/114389944-ef2bf580-9b95-11eb-8264-dee73bedcee8.png)

**Comment by tbrlpld** [comment]
This has been addressed in #94
