### ISSUE TITLE
Style page content TOC (on the right) according to design

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#86]
https://www.figma.com/file/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-wagtail.io?node-id=0%3A1

<img width="346" alt="Screen Shot 2021-04-08 at 20 43 19" src="https://user-images.githubusercontent.com/24797493/114139708-155a4880-98ab-11eb-8aa3-018bbf0162e8.png">

**Comment by PaarthAgarwal** [comment]
Since we have opted for gray to de-emphasize the table of page content, is this issue still relevant?

**Comment by tbrlpld** [comment]
Thanks for pointing this out. You are right, this one has been addressed.

**Comment by PaarthAgarwal** [comment]
> Thanks for pointing this out. You are right, this one has been addressed.

Glad to hear. Can you help me with this issue I'm facing https://github.com/wagtail/sphinx_wagtail_theme/commit/f7b5dd645114a3facb02647052d91d530a11735b#commitcomment-72749727?

**Comment by tbrlpld** [comment]
I have the same issue. Can you open a GitHub issue for that?

**Comment by PaarthAgarwal** [comment]
Sure
