### ISSUE TITLE
Sticky and scrollable TOC on the right

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#9]
Based on: https://github.com/wagtail/wagtail/issues/6793

We would like to have the TOC for the current page be shown on the right hand side of the page. 

The TOC should be sticky and scrollable (important for long TOCs).

**Comment by PaarthAgarwal** [comment]
I'll give it a try.

**Comment by PaarthAgarwal** [comment]
I have made Page TOC sticky but having some trouble while trying to make it scrollable. Besides the global TOC can also use being scrollable especially when the examples section is expanded. Opening a PR making the Page TOC sticky, will address scrollability either through further commits or maybe a new PR targeting both TOCs.

**Comment by PaarthAgarwal** [comment]
This issue can be closed now
